"""add discount percent to price group

Revision ID: 0c24be2b1198
Revises: e6e81e7b1669
Create Date: 2026-09-21 21:22:01.924258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c24be2b1198'
down_revision: Union[str, None] = 'e6e81e7b1669'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price_group', sa.Column('discount_percent', sa.Numeric(precision=5, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('price_group', 'discount_percent')
    # ### end Alembic commands ###
