"""add unit_cost to stock history

Revision ID: 102e133fb766
Revises: 0c24be2b1198
Create Date: 2026-09-22 20:03:19.600507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '102e133fb766'
down_revision: Union[str, None] = '0c24be2b1198'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_history', sa.Column('unit_cost', sa.Numeric(precision=12, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock_history', 'unit_cost')
    # ### end Alembic commands ###
