"""restrict price group deletion while assigned to users

Revision ID: 3caebc13b026
Revises: 695d85675711
Create Date: 2026-09-20 16:19:05.468148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3caebc13b026'
down_revision: Union[str, None] = '695d85675711'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('user_price_group_id_fkey'), 'user', type_='foreignkey')
    op.create_foreign_key(None, 'user', 'price_group', ['price_group_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.create_foreign_key(op.f('user_price_group_id_fkey'), 'user', 'price_group', ['price_group_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
